param(
    [string]$OutputPath,
    [string]$Version,
    [string]$DateVersion,
    [string]$BuildNumber
)

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$content = @"
// <auto-generated>
// This file is automatically generated during build.
// Do not modify manually - changes will be overwritten.
// </auto-generated>

/// <summary>
/// Contains application version information, automatically generated during build.
/// </summary>
/// <remarks>
/// Version format: yyyy.MM.dd.BuildNumber
/// - yyyy.MM.dd: Build date
/// - BuildNumber: Incremental build number (resets daily)
/// </remarks>
internal static class VersionInfo
{
    /// <summary>
    /// Gets the full version string (e.g., "2025.01.27.5").
    /// </summary>
    public const string Version = "$Version";

    /// <summary>
    /// Gets the date portion of the version (e.g., "2025.01.27").
    /// </summary>
    public const string DateVersion = "$DateVersion";

    /// <summary>
    /// Gets the build number (resets daily).
    /// </summary>
    public const string BuildNumber = "$BuildNumber";

    /// <summary>
    /// Gets the build timestamp.
    /// </summary>
    public const string BuildTimestamp = "$timestamp";
}
"@

# Ensure directory exists
$dir = Split-Path -Parent $OutputPath
if (!(Test-Path $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

# Write file
[System.IO.File]::WriteAllText($OutputPath, $content, [System.Text.Encoding]::UTF8)

Write-Host "Generated version file: $OutputPath"
Write-Host "Version: $Version"
